### ISSUE TITLE
Expose the existing tags filter in memory search options

### ISSUE THREAD

**Issue by bcdonadio** [donadiosolutions/lcm#988]
**Observed behavior:** The public TypeScript `MemoryApi.search` options omit `tags`, so an ordinary object-literal call with `{ cwd: projectPath, tags: ["decision"] }` fails excess-property checking once cwd is available, while the daemon `/search` route already accepts `tags` and filters promoted memory results by them. Existing JavaScript callers can send the field through the options spread, but typed callers cannot express the supported option directly.

**Expected behavior:** The public search option type should expose the existing daemon tags filter without changing its promoted-only semantics, with a typed transport regression and user-facing documentation.

**Root cause:** `src/memory/index.ts` declares only limit, threshold, projectId, and layers at default branch `de0362ad77537eb2007178ca759a7204d177136f`. `src/daemon/routes/search.ts` destructures `tags`, derives `filterTags`, and passes it to `project.lexicalSearch.searchPromoted`.

**How to reproduce safely:** In an isolated checkout, inspect `Parameters<MemoryApi["search"]>[1]` or typecheck `api.search("needle", { tags: ["decision"] })`: `tags` is not declared. No live daemon or database is needed. Add a mock-client assertion that the typed tags option crosses the HTTP JSON boundary unchanged; preserve episodic results' existing unfiltered behavior.

Distinct from #972 (missing project cwd option), #898 (SQLite promoted filtering order, merged), and #864 (episodic candidate strategy, merged). Discovered in Bug #972 GLM planning review; outside immutable S1 and not part of the #972 increment.

**Environment:**
- Agent: Codex Bug #972 owner with GLM-5.3 planning review
- Connector: static TypeScript client/daemon contract review
- OS: Fedora Linux

**Comment by bcdonadio** [comment]
Triage against the frozen S2 baseline `c284c767fa9b38d908773f968d214b145d16bac9` and current `origin/main` `d5d6d64f4bdf8f9c3f30d8e6499e8243b2cc82da`: **REPRODUCIBLE; keep open for remediation.**

Evidence:

- The frozen baseline's `src/memory/index.ts:9-12` declares `MemoryApi.search` options as `limit`, `threshold`, `projectId`, and `layers`; `tags` is absent. The same omission remains on current `origin/main` line 11 after #972 added `cwd`.
- The daemon already accepts and applies this field: `src/daemon/routes/search.ts:24-41` destructures `tags`, derives `filterTags`, and passes it to `project.lexicalSearch.searchPromoted(query, normalizedLimit, filterTags)` in the promoted layer. The public client implementation forwards options unchanged at `src/memory/index.ts:21-23`, so runtime JavaScript can send `tags`, but typed TypeScript callers cannot express the supported option.
- In an isolated checkout of current `origin/main` (`d5d6d64f4bdf8f9c3f30d8e6499e8243b2cc82da`), the following harmless fixture was typechecked with Node 25.9.0's repository toolchain:

  ```ts
  declare const api: MemoryApi;
  api.search("needle", { cwd: "/tmp/private-fixture", tags: ["decision"] });
  ```

  `tsc --ignoreConfig --noEmit --strict --target ES2022 --module NodeNext --moduleResolution NodeNext --skipLibCheck --types node --typeRoots /mnt/worktrees/62d7/lcm/node_modules/@types repro.ts` failed specifically with:

  ```text
  repro.ts(7,53): error TS2353: Object literal may only specify known properties, and 'tags' does not exist in type '{ limit?: number | undefined; threshold?: number | undefined; projectId?: string | undefined; layers?: SearchLayerInput[] | undefined; cwd?: string | undefined; }'.
  ```

  This is the reported excess-property failure after the separate `cwd` contract repair in #972. No daemon, database, credentials, or host state was used.

Duplicate check: no duplicate found. #972 covered only the missing `cwd` project-selection option and is now closed by its merged fix; #898 covers SQLite promoted FTS filtering after the SQL limit; #864 covers episodic candidate recall and tag semantics. Searches for `memory search`, `search options`, and tag-related issue titles found no other matching open or closed canonical issue. #988 is a distinct public TypeScript contract omission.

Environment: Fedora Linux, Node 25.9.0, isolated detached checkout and private type fixture only.

**Comment by bcdonadio** [comment]
Correction to the baseline identifier in the preceding triage note: the S2 campaign brief freezes triage at `ad2dd1ec944e8eb0a2e51f5397de86591cb6e75f` (not `c284c767fa9b38d908773f968d214b145d16bac9`). The same isolated type reproduction was rerun from a detached checkout of the exact frozen SHA and produced the same excess-property error: `tags` does not exist in the `MemoryApi.search` options type. Current `origin/main` `d5d6d64f4bdf8f9c3f30d8e6499e8243b2cc82da` retains the omission.
